sudo: true
language: scala

scala:
  - 2.12.11
  - 2.13.3

dist: trusty
group: edge

jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

# coverage temporary disabledcoverage
# sbt ++$TRAVIS_SCALA_VERSION Report;
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean validate

after_success: bash <(curl -s https://codecov.io/bash)
